/** @format */

export const INFRA_ERROR_CODES = {
    DATABASE_GENERAL_ERROR: "10000",
    DATABASE_CONNECTION_CREATION_ERROR: "10001",
    DATABASE_QUERY_EXECUTION_ERROR: "10002",
    DATABASE_QUERY_TRANSACTION_ERROR: "10003",
    DATABASE_BATCH_QUERY_EXECUTION_ERROR: "10004",
};

export const DEFAULT_HTTP_HOST = "0.0.0.0";
export const DEFAULT_HTTP_PORT = 30010;

export const DEFAULT_REQUEST_LANGUAGE_ITEM = "language";
